   <section>
        <div id="banner" class="two ">
          <span class="opaque"></span>
          <svg
            class="svgTop flipped"
            width="1866"
            height="60"
            viewBox="0 0 1866 60"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path d="M1866 60L0 60L1866 0.00012207V60Z" fill="#232325" />
          </svg>

          <svg
            class="svgBottom flipped"
            width="1866"
            height="60"
            viewBox="0 0 1866 60"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
          >
            <path
              d="M5.24535e-06 9.01081e-07L1866 0.000164032L0 59.9998L5.24535e-06 9.01081e-07Z"
              fill="#121213"
            />
          </svg>

          <div class="contentContainer">
            <h4>GOT TECHNOLOGY TROUBLES?</h4>
            <a href="#"><button class="headerButton">WE CAN HELP YOU!</button></a>
          </div>
        </div>
      </section>