<section>
  <div id="banner" class="one">
    <span class="opaque"></span>
    <svg
      class="svgBottom"
      width="1866"
      height="60"
      viewBox="0 0 1866 60"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path d="M1866 60L0 60L1866 0.00012207V60Z" fill="#232325" />
    </svg>

    <svg
      class="svgTop"
      width="1866"
      height="60"
      viewBox="0 0 1866 60"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <path
        d="M5.24535e-06 9.01081e-07L1866 0.000164032L0 59.9998L5.24535e-06 9.01081e-07Z"
        fill="#121213"
      />
    </svg>

    <div class="contentContainer">
      <h4 data-aos="fade-right">
        IF WE CAN'T FIX THE PROBLEM, YOU DON'T PAY ANYTHING!
      </h4>
      <a href="#"><button class="headerButton">SEE OUR PRICING</button></a>
    </div>
  </div>
</section>
