<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Andratech</title>
    <link rel="stylesheet" href="./assets/css/main.css" />
    <link
      href="https://fonts.googleapis.com/css2?family=Oswald:wght@600&family=Montserrat&display=swap"
      rel="stylesheet"
    />
    <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet" />
  </head>
</html>
