<div id="header">
  <div id="fullLogoContainer">
    <div id="logoFull">
      <img src="./assets/img/logo.svg" alt="Andratech Logo" />
    </div>
    <nav>
      <div id="navContainer">
        <div class="hamburger">
          <div class='line1'></div>
          <div class='line2'></div>
          <div class='line3'></div>
        </div>
        <div class="  ">
        <a class="hidden left" href="#"
          ><div class="logoSmall">
            <img src="./assets/img/logo-small.svg" alt="" /></div
        ></a>
        </div>
        <ul class="navbarUL">
          <li><a href="./index.php">HOME</a></li>
          <li><a href="./services.php">SERVICES</a></li>
          <li><a href="./pricing.php">PRICING</a></li>
          <li><a href="./about-us.php">ABOUT US</a></li>
          <li><a href="./our-work.php">OUR WORK</a></li>
        </ul>         
            <a href="./contact.php"
              ><button class="headerButton">FREE QUOTE</button></a>
          
        </ul>
      </div>
    </nav>
  </div>
</div>
