<div id="header">
  <div id="fullLogoContainer">
    <div id="logoFull">
      <img src="./assets/img/logo.svg" alt="Andratech Logo" />
    </div>
    <nav>
      <div id="navContainer">
        <a class="hidden left" href="#"
          ><div class="logoSmall">
            <img src="./assets/img/logo-small.svg" alt="" /></div
        ></a>
        <ul>
          <li><a href="#">HOME</a></li>
          <li><a href="#">SERVICES</a></li>
          <li><a href="#">PRICING</a></li>
          <li><a href="#">ABOUT US</a></li>
          <li><a href="#">OUR WORK</a></li>

          <li>
            <a href="#"><button class="headerButton">FREE QUOTE</button></a>
          </li>
        </ul>
      </div>
    </nav>
  </div>
</div>
