 <div id="hero">
          
          <video
            id="heroVideo"
            src="./assets/video/hero.mp4"
            poster="./assets/img/video-poster.jpg"
            muted
            loop
            autoplay
          ></video>
          <span>
            <div class="heroHeader">
              TECH SUPPORT WHEN YOU NEED IT

              <div class="heroHeaderSubContainer">
                <div class="heroHeaderSubLeft">
                  24 Hours A Day <b>/</b> 7 Days A Week
                </div>
                <div class="heroHeaderSubBottom">
                  Servicing North Brisbane and surrounding areas
                </div>
              </div>
              <div class="buttonCont">
                <button>GET AN OBLIGATION FREE QUOTE</button>
              </div>
            </div>
          </span>
        </div>