<div
  style="
    width: 100%;
    display: flex;
    justify-content: center;
    align-items: center;
  "
>
  <iframe
    width="600px"
    height="330px"
    frameborder="0"
    scrolling="no"
    marginheight="0"
    marginwidth="0"
    src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=Andratech%20Computing,%2045%20Brickworks%20Road,%20Kallangur,%20Qld,%204503+(Andratech%20Computing)&amp;t=&amp;z=15&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"
  >
  </iframe>
</div>
