  <section id="servicesContainer">
        <div id="services">
          <div class="box-left">
            <h4>HOW WE CAN HELP YOU</h4>
            <div class="headingUnderline"></div>
            <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Exercitationem commodi vitae magni? Iste porro quos optio reiciendis alias sed reprehenderit atque laudantium. Sint sit, maxime possimus obcaecati amet quis inventore! </p>
            <img src="./assets/img/how-we-can-help.svg" alt="">
          </div>
          <div class="box-right">
            <div class="tickLine">
              <img src="./assets/img/tick.svg" alt="Tick">
              <p>Lorem ipsum, dolor sit amet consectetur</p>
            </div>
            <div class="tickLine">
              <img src="./assets/img/tick.svg" alt="Tick">
              <p>Lorem ipsum, dolor sit amet consectetur</p>
            </div>
            <div class="tickLine">
              <img src="./assets/img/tick.svg" alt="Tick">
              <p>Lorem ipsum, dolor sit amet consectetur</p>
            </div>
            <div class="tickLine">
              <img src="./assets/img/tick.svg" alt="Tick">
              <p>Lorem ipsum, dolor sit amet consectetur</p>
            </div>
            <div class="tickLine">
              <img src="./assets/img/tick.svg" alt="Tick">
              <p>Lorem ipsum, dolor sit amet consectetur</p>
            </div>
            <div class="tickLine">
              <img src="./assets/img/tick.svg" alt="Tick">
              <p>Lorem ipsum, dolor sit amet consectetur</p>
            </div>
            <div class="tickLine">
              <img src="./assets/img/tick.svg" alt="Tick">
              <p>Lorem ipsum, dolor sit amet consectetur</p>
            </div>
            


          </div>
        </div>
        


      </section>