  
      <section id="visitUs">
        
        <div id="visitUsContainer">
          
          <div id="visitText">
            <h5>Andratech Computing</h5>
            <p>Open 24 / 7</p>
            <p>Apppintment Only</p>
          </br>
            <p>45 Brickworks Rd</p>
            <p>Kallangur QLD</p>
            <p>4503</p>
            <br />
            <p><code>0422</code> <code>401</code> <code></code>487</code> </p>
            <br>
            <p>xeontranq<code>@</code>live.com</p>
          </div>
          
          <div style="width: 100%;display: flex;justify-content: center;align-items: center;">
            <iframe width="600px"  height="330px" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com/maps?width=100%25&amp;height=600&amp;hl=en&amp;q=Andratech%20Computing,%2045%20Brickworks%20Road,%20Kallangur,%20Qld,%204503+(Andratech%20Computing)&amp;t=&amp;z=15&amp;ie=UTF8&amp;iwloc=B&amp;output=embed"></iframe></div>
        </div>
      </section>