  
<section id="visitUs">
    <div id="visitUsContainer">
        <div id="visitText">
            <h5>Andratech Computing</h5>
            <p>Open 24 / 7</p>
            <p>Apppintment Only</p>
            </br>
            <p>45 Brickworks Rd</p>
            <p>Kallangur QLD</p>
            <p>4503</p>
            <br />
            <p><code>0422</code> <code>401</code> <code></code>487</code> </p>
            <br>
            <p>xeontranq<code>@</code>live.com</p>
        </div>

        <?php include "./inc/map.inc"?> 
    </div>
</section>