<section>
        <div id="whyChooseUsContainer">
          <div id="whyChooseUs">
            <div class="sectionHeadingContainer">
              <h2>WHY CHOOSE US?</h2>
              <div class="headingUnderline"></div>
            </div>
            <div class="boxContainer">
              <div class="box">
                <div class="iconBox">
                  <div class="icon">
                    <img src="./assets/img/money.svg" alt="money symbol" />
                  </div>
                </div>
                <div class="textBox">
                  <h3>No Fix, No Charge</h3>
                  <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Facilis quidem ea recusandae officia enim nihil repudiandae
                    tenetur eveniet.
                  </p>
                </div>
              </div>
              <div class="box">
                <div class="iconBox">
                  <div class="icon">
                    <img src="./assets/img/cal.svg" alt="cal symbol" />
                  </div>
                </div>
                <div class="textBox">
                  <h3>24/7, 365 Days a Year</h3>
                  <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Facilis quidem ea recusandae officia enim nihil repudiandae
                    tenetur eveniet.
                  </p>
                </div>
              </div>
              <div class="box">
                <div class="iconBox">
                  <div class="icon">
                    <img src="./assets/img/people.svg" alt="avatar" />
                  </div>
                </div>
                <div class="textBox">
                  <h3>Friendly Technicians</h3>
                  <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Facilis quidem ea recusandae officia enim nihil repudiandae
                    tenetur eveniet.
                  </p>
                </div>
              </div>
              <div class="box">
                <div class="iconBox">
                  <div class="icon">
                    <img src="./assets/img/clean.svg" alt="avatar" />
                  </div>
                </div>
                <div class="textBox">
                  <h3>Free System Sanitize</h3>
                  <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit.
                    Facilis quidem ea recusandae officia enim nihil repudiandae
                    tenetur eveniet.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>